### ISSUE TITLE
Figure out what is causing grief on k8s 1.23

### ISSUE THREAD

**Issue by vaikas** [sigstore/scaffolding#81]
This passed with 1.21 and 1.22 but 1.23 seemed to be timing out jobs since looked like they were only retried 6 times. Is this a new behaviour or did something else change?
https://github.com/sigstore/cosign/runs/5697562612?check_suite_focus=true

**Comment by vaikas** [comment]
Ok, so here's a problem and surely it looks to be with 1.23 version of kind.

```
kind create cluster --name 1.23 --kubeconfig /Users/vaikas/kind-kubeconfig --image kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
```

create a simple job:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: checktree
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: checktree
          image: ghcr.io/sigstore/scaffolding/checktree@sha256:4743ba4fdbbe305dafb70474ac4aeb9d23a36acdd38f7c1677de56d2f5ed35e0
```
No, I mean like really create the job:

```
kubectl --context kind-1.23 --kubeconfig /Users/vaikas/kind-kubeconfig create -f ~/Downloads/checktree.yaml
```

Then you can watch pods spinning up without proper backoff:
```
vaikas@villes-mbp chains % kubectl --context kind-1.23 --kubeconfig /Users/vaikas/kind-kubeconfig get pods
NAME              READY   STATUS   RESTARTS   AGE
checktree-49v25   0/1     Error    0          7s
checktree-8z9gg   0/1     Error    0          8s
checktree-hwpd7   0/1     Error    0          9s
checktree-kbddb   0/1     Error    0          15s
checktree-l4c8g   0/1     Error    0          4s
checktree-pbz7p   0/1     Error    0          5s
checktree-xjt7c   0/1     Error    0          6s
```

Note they all run in a matter of ~15 seconds, and after 7 of them (default being 6 retries). So, there's no backoff.
